### ISSUE TITLE
Custom donation amount on screen 1 should allow validation against a configurable minimum value

### ISSUE THREAD

**Issue by jshelley** [Ophidian-AC/charcomponent#5]

**Comment by Ophidian-AC** [comment]
Jordan, the minimum should already be configurable, it's in the configOptions object.  Right now I have it at 1, and on clicking the form it won't let you go lower than 1, but changing the minimum will also change the minimum allowed there. Or did you mean something else?

**Comment by jshelley** [comment]
Sorry I didn't see that it was in the configuration object. However, I currently can type 0 in the field and then press the next button without any errors.

**Comment by Ophidian-AC** [comment]
Understood, I'll take care of it!
